[package]
name = "toycomp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "regex-cli"
[[bin]]
name = "compiler"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
